Add files via upload
RUR-5996/FRC2019Mecanum pull request #13
Opened 2019-02-01 10:05 UTC by OTK87

First version of our linetracker code.

2019-02-01 10:10 UTC, razhakin requested changes
Add comments, naming -> stick to Subsystem and Command naming, set higer values for Y driving -> mecanum is weird at low speed, range boundaries for raw values (might not always be 1000)

2019-02-06 20:46 UTC, KaplanL approved these changes

2019-02-06 20:46 UTC, KaplanL approved these changes

2019-02-17 12:17 UTC, razhakin commented
Removed due to inactivity.

2019-02-17 12:17 UTC, closed without merging