Comments, abstractization
RUR-5996/FRC2019Mecanum pull request #25
Opened 2019-02-02 21:16 UTC by razhakin

2019-02-02 21:23 UTC, KaplanL approved these changes

2019-02-03 11:12 UTC, Statej requested changes

2019-02-03 11:12 UTC, Statej commented on Constants.java
> +    public static final double shootingTime = 0.5;
This specifies for how long will the shooter spin? I would say that for anything which is not 100% clear we should include a short comment saying what it is. e.g. // time specifying how long will the shooter wheels spin

2019-02-03 11:12 UTC, Statej commented on Constants.java
>      //Bosch motor speed
In the above line 40 please add comment saying when is this timeout used

2019-02-03 11:12 UTC, Statej commented on commands/ShootCommand.java
>    /**
missing docs

2019-02-03 11:12 UTC, Statej commented on subsystems/RotateSubsystem.java
>    /**
rewrite the below sentence please

2019-02-03 11:15 UTC, closed without merging